import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/common/Header';
import Navbar from '@/components/module/Navbar';
import { Box, Toolbar } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<header>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Istok+Web&display=swap"
				/>
			</header>
			<body className={inter.className}>
				<Box className="w-screen h-screen flex bg-dark_background_grey">
					<Header />
					<Navbar />
					<Box className="grow px-32 py-32">
						<Toolbar />
						{children}
					</Box>
				</Box>
			</body>
		</html>
	);
}
